### ISSUE TITLE
Migrate Issues over from tombatossals/angular-leaflet-directive

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#1]
Attempt to use https://github.com/google/github-issue-mover

**Comment by nmccready** [comment]
Ahh the joys of not having ownership transferral. So far github has blocked me and I am stuck at tombatossals/angular-leaflet-directive#818 . Will progress some more when then rate limit expires.

**Comment by nmccready** [comment]
Currently the only thing that semi works for migrating issues is https://github-issue-mover.appspot.com/ , however it does close issues (move) on original repo (not desired). Be nice to have a fork of this project where you have the option to copy and do bulk migration.

Nice to haves:

- bulk migration
- use github api in a offical manner to not hit rate limits
- option to copy / clone issues and PRS besides moving

**Comment by nmccready** [comment]
Also migrate issues from old milestones into new milestones. #71

**Comment by nmccready** [comment]
@jessertaylor @elesdoar @zacronos feel free to migrate issues over ; please post on here where you started and ended from https://github.com/tombatossals/angular-leaflet-directive/

**Comment by nmccready** [comment]
Most issues have been migrated. The 20 so that have been missed were more than a year old so I am not including them. If they are important, they will come up again.

**Comment by nmccready** [comment]
@jessertaylor @elesdoar please note

**Comment by elesdoar** [comment]
:+1:
