### ISSUE TITLE
Attribution: How to disable "Leaflet" from showing up?

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#110]
_From @devourment77 on September 14, 2015 14:25_

Here is the layers object I am using and the custom attribution is showing correctly, but it has a prefix "Leaflet" that I was not sure how to toggle?

```
$scope.map.layers = {
    baselayers: {
        mapbox_terrain: {
            name: 'Mapbox Terrain',
            url: 'http://api.tiles.mapbox.com/v4/{mapid}/{z}/{x}/{y}.png?access_token={apikey}',
            type: 'xyz',
            layerOptions: {
                apikey: '...',
                mapid: 'mapbox.streets',
                attribution: '&copy; <a href="http://maponics.com" target="_blank">Maponics</a> &amp; <a href="" target="_blank">MapBox</a>'
            }
        }
    }
};
```

_Copied from original issue: tombatossals/angular-leaflet-directive#939_

**Comment by nmccready** [comment]
_From @simison on September 14, 2015 14:52_

I'm doing this by first setting `attributionControl: false` and then:

```javascript
    leafletData.getMap('map-canvas').then(function(map) {
      map.addControl(L.control.attribution({
        position: 'bottomright',
        prefix: ''
      }));
    });
```

...where map-canvas is the id: `<div id="map-canvas" ...></div>`. A bit cumbersome indeed.

A separate `attributionPrefix` option would suffice.

**Comment by nmccready** [comment]
_From @seadour on September 15, 2015 17:28_

+1!

Thanks @simison for posting your solution here

**Comment by RodolfoSilva** [comment]
This worked for me:
```javascript
$scope.$on('leafletDirectiveMap.map.load', function (event, data) {
  var map = data.leafletObject;
  map.attributionControl.setPrefix(false);
});
```

**Comment by simison** [comment]
This could be added to documentation. Someone PR? :-)

**Comment by nmccready** [comment]
Closing, feel free to add to the docs or wiki.

**Comment by davidrhoderick** [comment]
None of these worked for me. @nmccready's gave me an error for `L` not being defined and @RodolfoSilva's didn't do anything.  Couldn't find anything in the documentation either.  Am I missing something or are these fixes no longer working?

**Comment by simison** [comment]
@davidovich works for me here:

First setting it to `false`: https://github.com/Trustroots/trustroots/blob/5a1ca60347c73b0ee203f82255cf791a967c79d4/modules/search/client/controllers/search.client.controller.js#L67

Then adding it manually: https://github.com/Trustroots/trustroots/blob/5a1ca60347c73b0ee203f82255cf791a967c79d4/modules/search/client/controllers/search.client.controller.js#L133-L141

**Comment by davidrhoderick** [comment]
Do you use jshint?  I have a Yeoman-scaffolded Grunt-run project and I can't (for whatever reason) disable an undefined variable (`// jshint undef: false` doesn't work).  How would you deal with the undefined variable `L`?
