### ISSUE TITLE
Drag map through paths

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#114]
_From @cyrilchaponeverysens on September 21, 2015 7:46_

In the [leaflet examples](http://leafletjs.com/examples/quick-start.html), if you **click & drag** a path, the map moves.

In the [angular-leaflet examples](http://tombatossals.github.io/angular-leaflet-directive/examples/0301-paths-types-example.html), this only works with `mutlipolygon` & `multipolyline` type.

I know I can disable pointer-events on my paths, setting clickable = false, but one really needs to move map through Polygons plus keeping the ability to have pointer events on it (including _label_, _popup_, _hover_ features)

_Copied from original issue: tombatossals/angular-leaflet-directive#952_

**Comment by nmccready** [comment]
_From @vlavellauruit on October 13, 2015 21:13_

@cyrilchaponeverysens  facing the same issue... any idea about how can I achieve this?

**Comment by nmccready** [comment]
_From @cgat on October 19, 2015 20:33_

I've been over the code a few times and can't figure this one out. If anyone makes progress, I'd like to be kept in the loop.

**Comment by dallingel** [comment]
Hello,
I am experiencing the same issue. It seems to be an event propagation issue, seems on a polygon, the "drag" event isn't propagated, or cancelled somewhere.
Is someone working on that issue? I could try to find it...

**Comment by dasdany** [comment]
@dallingel could you please find out how to fix this? I've the same problem.

**Comment by nmccready** [comment]
@dasdany there is actually a simple way around this via CSS.

http://gis.stackexchange.com/questions/116065/how-to-let-leaflet-layer-events-to-propagate-to-layer-below

You need to find the element which is the path maybe even add a custom class for those paths. Depending on the scenario you will do `pointer-events:none/auto`
