### ISSUE TITLE
fix examples to point to leaflet 1.0.0-beta ..

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#123]
_From @nmccready on September 30, 2015 19:54_

So the old path

`<script src="../bower_components/leaflet/dist/leaflet.js"></script>` is now at

`<script src="../bower_components/leaflet/leaflet.js"></script>`

as well as the css.

`<link rel="stylesheet" href="../bower_components/leaflet/dist/leaflet.css" />`

`<link rel="stylesheet" href="../bower_components/leaflet/leaflet.css" />`

This might be reverted to dist depending on what leaflet does about the bower situation. See #851

_Copied from original issue: tombatossals/angular-leaflet-directive#967_

**Comment by elesdoar** [comment]
Leaflet 1.x still dist folder as distribution release.
