### ISSUE TITLE
Fix travis leaflet dependency for 1.0.0 leaflet

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#131]
_From @nmccready on October 12, 2015 14:44_

https://travis-ci.org/realtymaps/realtymaps/angular-leaflet-directive/builds/82999172

_Copied from original issue: tombatossals/angular-leaflet-directive#991_

**Comment by elesdoar** [comment]
Solve in 9c21121762bbb6e42a0cd24f579a6eaac54c2160 commit.
