### ISSUE TITLE
font-awesome bower dependency

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#148]
_From @nmccready on March 23, 2015 20:20_

https://github.com/tombatossals/angular-leaflet-directive/blob/master/bower.json#L16

Should this not be a devDependency?

_Copied from original issue: tombatossals/angular-leaflet-directive#663_

**Comment by nmccready** [comment]
@tombatossals

**Comment by nmccready** [comment]
I'll dig into this

**Comment by nmccready** [comment]
@tombatossals @jessertaylor do u guys know why this is a dependency? Is it really or just a devDep?

**Comment by nmccready** [comment]
_From @jessertaylor on April 20, 2015 13:7_

It's because of https://github.com/lvoogdt/Leaflet.awesome-markers

**Comment by nmccready** [comment]
Right but the plugin is optional, so it should be a devDep and not forced upon everyone. One of the problems is font-awesome appears to be in bower in a few different ways. Thus this causes duplicate downloads of font-awesome by needing this library.

**Comment by elesdoar** [comment]
It's needed for some plugins, I closing this issue for now.
