### ISSUE TITLE
ES5 Strict Mode Problems

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#151]
_From @stefan-niedermann on April 1, 2015 9:40_

Compiling with Google Closure i get the following problem:

Apr 01, 2015 11:38:12 AM com.google.javascript.jscomp.LoggerErrorManager println
SCHWERWIEGEND: script.js:618: ERROR - "arguments.callee" cannot be used in ES5 strict mode

_Copied from original issue: tombatossals/angular-leaflet-directive#671_

**Comment by nmccready** [comment]
Did you dig into the code base or give us more specifics of the offending line? We need people to make an effort.

**Comment by stefan-niedermann** [comment]
sorry, i have very little time and multiple open source projects i already contribute to... maybe some day if i have more time...

**Comment by nmccready** [comment]
Ok, when you feel like it; ping back and I will re-open.
