### ISSUE TITLE
Google maps and Overlays out of sync while zooming

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#168]
_From @robotnic on November 27, 2014 16:42_

When the map is zoomed first the Overlay animation appears and after that the google maps animation starts. 

Openlayers has a nicer zoom animation I think - no idea how they do it.
http://openlayers.org/en/v3.0.0/examples/google-map.html

But it's also not in sync. 

_Copied from original issue: tombatossals/angular-leaflet-directive#552_

**Comment by nmccready** [comment]
_From @robotnic on November 27, 2014 16:44_

leaflet example:
http://tombatossals.github.io/angular-leaflet-directive/examples/googlemaps-example.html

**Comment by nmccready** [comment]
_From @dud3 on January 22, 2015 14:11_

Same here.

**Comment by nmccready** [comment]
_From @dud3 on April 16, 2015 13:44_

@tombatossals Any new over here ?

**Comment by dud3** [comment]
@nmccready `bower install ul-leaflet` says: `ENOTFOUND Package ul-leaflet not found` any ideas ?

**Comment by nmccready** [comment]
It's there 
```
bower lookup ui-leaflet
ui-leaflet git://github.com/angular-ui/ui-leaflet.git
```

Try updating your bower, `npm install -g bower`

**Comment by dud3** [comment]
Yep that worked.

**Comment by dud3** [comment]
In this example: http://angular-ui.github.io/ui-leaflet/#!/examples/google-maps seems to work pretty well, it'll probably take me some time to migrate to my project, thanks.

**Comment by nmccready** [comment]
So we can close?

**Comment by elesdoar** [comment]
I think so, I closing this issue, reopen if you think is necessary.

**Comment by dud3** [comment]
Yep, I think it can stay closed for now, everything seems to be working fine.
