### ISSUE TITLE
About the Control of the opacity of layer

### ISSUE THREAD

**Issue by fionaleews** [angular-ui/ui-leaflet#171]
Dear folks,
is there any example about adding opacity control for 'xyz' layer?
I just find that the example of marker's opacity only in the documentation.
I would like to add the value control bar to control the 'xyz' layer, no matter in or out of the map.
like this one:

http://lizardtechblog.github.io/Leaflet.OpacityControls/

Please help for sharing your codes about it if you guys have one!
Thanks a lot!

**Comment by elesdoar** [comment]
Please check http://angular-ui.github.io/ui-leaflet/examples/0000-viewer.html#/controls/custom-layer-control-example

Click on double down arrow in layer manager.

![gh](https://cloud.githubusercontent.com/assets/3817595/10913527/4f2ef73c-821c-11e5-8bd5-4614a23a689b.png)

**Comment by fionaleews** [comment]
Thanks a lot^^~~
