### ISSUE TITLE
Angular 2.x

### ISSUE THREAD

**Issue by AleRob90** [angular-ui/ui-leaflet#178]
Hi,
This is more a question than an issue, but let ask:
Will ui-leaflet be ported to angular 2.x? I know right now angular2 is in alpha state, but next year we can use it in production from what i've heard.
I wanna start a new project and i'm kinda confused what should i do. I want angular2 in my project, but it seems a little to complicated to start right now with it.

Thx in advance.

**Comment by nmccready** [comment]
Our goal and priority right now is to support the next version of leaflet (1.X). The next thing after that might be angular 2. I think @elesdoar states some interest in this. As for me I am not sold on angular2 . So with that said yes if people want to join in and lead the way.

**Comment by elesdoar** [comment]
I am interested in this, but I must investigate about Angular 2, I think that a version based on Angular 2 should be in another repo as it will be written in another language (typescript). Though, this is a future plan.

**Comment by elesdoar** [comment]
I was investing about angular 2, the API change totally, we would have than rewrite all the directive, in this way, as I said, we should create another repo right from the start. I am willing to start with this, but it would need a lot of work and collaboration.

**Comment by Shawn-Fan** [comment]
Good idea! will you try it?

**Comment by elesdoar** [comment]
Yeah, angular2 is in beta state, I'll try write ui-leaflet for angular2 and leaflet 1 when I have some free time, I hope will be soon. When I start with this, I'll notify it
