### ISSUE TITLE
Separate not core leaflet layers in a plugin.

### ISSUE THREAD

**Issue by elesdoar** [angular-ui/ui-leaflet#191]
Separate mapbox, cartodb, google, esri and anothers layers in a new plugin for ui-leaflet.

Change local function to service provider.
https://github.com/angular-ui/ui-leaflet/blob/master/src/services/leafletLayerHelpers.js#L38-L438

**Comment by nmccready** [comment]
:+1:

**Comment by elesdoar** [comment]
I init a repo for it, I override MapboxGL for now, In the coming days I'll be migrating another layers. 

@nmccready  please check the new code in [here](https://github.com/elesdoar/ui-leaflet-layers/blob/master/dist/ui-leaflet-layers.js)

**Comment by elesdoar** [comment]
https://github.com/elesdoar/ui-leaflet-layers Plugin Repo

**Comment by nmccready** [comment]
Kick ass!
