### ISSUE TITLE
array of markers instead of object of markers fails to update on $scope change

### ISSUE THREAD

**Issue by furiousOyster** [angular-ui/ui-leaflet#199]
If markers are assigned to $scope using an array of markers, then a new array of different markers is assigned to replace them, the markers will be displayed correctly, but mouseevents will still refer to the original array.

It does not fix this issue to simply keep reusing the original array, as using Array.push.apply($scope.markers, newMarkers) has no difference on this bug occuring.

Switching to using objects instead of arrays to hold the markers resolves this issue.

This is a problem because using arrays KINDOF works - it works enough that you might not notice at first.  Or for many hours after....

Demo of this bug here: http://embed.plnkr.co/tEta4LZgNt0JKSD37f8H/preview

**Comment by furiousOyster** [comment]
Moreover, the two objects used as markers must have different key names for the markers they hold, or else the first marker to be assigned to a particular key will stick for all future mouse events.
This is probably the cause of the issue with arrays, too, since the index is being used as the key, and this repeats.
Something somewhere needs to refresh the bindings to the marker objects for mouse events every time the scope changes, as it seems to hold on to the first key it is given, which overrides any future changes.  Unique keys are unaffected by this.

**Comment by fionaleews** [comment]
HI furiousOyster!
Do u have any solution of this issue? i m suffering by this problem after filtering the markers in $watch.
Please let me know how do u solve it if you find any ways!
thanks so much!

cheers,
Fiona

**Comment by nmccready** [comment]
Use directive controls and abandoned the watch for now its buggy and known to have issues. Yes its not angular but it is lower overhead and can avoid the bugs. Also disable the watch.

https://github.com/angular-ui/ui-leaflet/blob/master/examples/0512-markers-clustering-10000-markers-example-no-watch.html

**Comment by nmccready** [comment]
#79

**Comment by nmccready** [comment]
Marking as dupe w workaround.

**Comment by seadour** [comment]
>Moreover, the two objects used as markers must have different key names for the markers they hold, or else the first marker to be assigned to a particular key will stick for all future mouse events.
>This is probably the cause of the issue with arrays, too, since the index is being used as the key, and this repeats.

I'm having a similar and probably related issue right now. When I change `$scope.markers`, the event listeners for the markers (e.g. `leafletDirectiveMarker.click`) still have `args` values from the old set of markers.

Related issue: https://github.com/angular-ui/ui-leaflet/issues/95
