### ISSUE TITLE
Debugging failure to render GeoJSON

### ISSUE THREAD

**Issue by jjcad** [angular-ui/ui-leaflet#205]
I've got a very bizarre issue.  I am building a website off of MEAN.js (private repo currently, because of client) and I've added a number of modules for displaying data and graphs and such, and I'm getting into displaying maps now.

I've been trying to make ui-leaflet work with the GeoJSON data and it is failing to render the polygons in the browser, and does not generate an error on the browser's console.  I can look at the scopes using Batarang and see that they're correctly populated, but they just don't show.

When I make an example using a pristine instance of MEAN.js the polygons do render, so I'm unable to duplicate the problem.  I've added the additional JS libraries that are called in other parts of the project to my pristine MEAN.js instance and that seems to have no impact.  I've overwrittent the module in my problem project with the module from my pristine project and there is still no impact.

I'm out of ideas for how to find out what is causing this issue.  Here's my example where I fail to reproduce the issue: https://github.com/jjcad/leaflet_meanjs_example
I'm open to any and all ideas about how to solve this.

**Comment by seadour** [comment]
When you inspect the map with your browser dev tools, can you see the DOM elements for the polygons? They should be in an `<svg>` element with the class `leaflet-zoom-animated`.

Here's a screenshot from my project - we have a lot of GeoJSON polygons, so there's a lot of `<g>...</g>` elements in the SVG, one per each polygon:

<img width="799" alt="screen shot 2015-12-14 at 10 56 59 am" src="https://cloud.githubusercontent.com/assets/6138182/11790669/d933f0d6-a251-11e5-8a51-21b6718b143c.png">

**Comment by jjcad** [comment]
In my linked example project & my problem project (which have identical map modules at the moment) I've downgraded to trying to show just one polygon (a square). In both of them, it is adding the `<svg>` and `<g>` elements.  I tried adding a screenshot from my problem project, but github is being disagreeable about that matter.  I'll mess with it a little more and see if I can add one or link to one.

**Comment by jjcad** [comment]
I am loading d3 and nvd3 for another module in the project.  Is it possible that those are creating a conflict?  If so, I'm still not sure why my example would show the polygon, but my problem project would not, since they're both loading d3 and nvd3 right now.  The difference is that nowhere in my example project are d3 and nvd3 actually used...

**Comment by nmccready** [comment]
I have used d3 in the past at it has some interesting low level issues if you muck with the date object. Your not by anychance using date.js? Just double checking as it will make d3 not work if your using a bad version of date..js

https://github.com/mbostock/d3/issues/1302

**Comment by nmccready** [comment]
As for why polygons are not showing; I really need a reproducible example.

**Comment by jjcad** [comment]
No date.js being used. I'm really wishing I could make a reproducible example, but all my attempts at making one that fails to render polygons have been thus far foiled. It seems like it only fails to work in my actual project, even when I import working code from a working example into my actual project.

**Comment by jjcad** [comment]
I did not mean to close that. I'm still going to keep trying to make a reproducible example and some screenshots.

**Comment by jjcad** [comment]
[Alright, here's an example.](https://github.com/jjcad/leaflet_meanjs_example/blob/master/example.png)

Also, I'm so sorry about the open/close thing. I keep hitting the wrong button when trying to post.

**Comment by jjcad** [comment]
Is there a way that I could figure out if d3 is maybe hijacking the `<svg>` element from leaflet?

**Comment by nmccready** [comment]
Sorry I can not derive anything from your image. Please make a plnkr or github repo that shows shows the problem. If we need to get into your server we can do that but that will need to be taken offline via email.

**Comment by jjcad** [comment]
Believe me, I would love to reproduce the problem. Every reproduction I make fails to make the problem occur though.

**Comment by seadour** [comment]
I'm guessing one of your extra libraries is causing a conflict. Maybe in your reproductions, you're not using the same versions of each library? (e.g. maybe your reproduction uses D3 version 3.5.11 but the problem is with D3 version 3.5.10)

In any case, this is next to impossible for us to help you troubleshoot without being able to see the problematic code. Keep trying to make a 'working' (non-working) version that successfully reproduces the issue, paying close attention to each additional library and its version number, as well as the order in which each library is loaded.

**Comment by jjcad** [comment]
@seadour Thanks for the good advice. I'll work on building that out.

**Comment by jjcad** [comment]
After several more attempts at building a non-working example, I still can't reproduce this error. Closing issue as a result.
