### ISSUE TITLE
Marker clustering and controller reset

### ISSUE THREAD

**Issue by claustres** [angular-ui/ui-leaflet#206]
I use the directive in a big single page application where the navigation between the pages is handled using angular ui-router, so the controllers are destoyed/created each time. I noticed that my markers were correctly loaded on the first map page visualisation but not on the subsequent page visualisations.

It seems that it is related to clustering. Indeed I add a 'group' property to my markers to create different clusters. Removing this property solved my issue. I suspect some data structures are not correctly cleaned when destroying the scope using marker clustering.

I started to jump into the source code trying to fix it but I raise this issue waiting to be more comfortable with the directive source code...

**Comment by nmccready** [comment]
Can you produce a small example? Also are the subsequent renderings from ajax calls if so this is a known problem. Basically you only workaround is to disable watches at the moment and use directiveControls to manually update.

**Comment by nmccready** [comment]
#79

**Comment by claustres** [comment]
Ok it might be related because each marker group is created through an Ajax request in my case. However this does work well without marker clustering, if so should it be the case ?

**Comment by nmccready** [comment]
Hmm ok then this could be a unique issue if it is fine otherwise. Can you make an example?

**Comment by claustres** [comment]
I will try to do so, just installed an environnment with Node 5 in order to build the directive. I contributed to https://github.com/tombatossals/angular-openlayers-directive and it seems to be similar on some aspects. Just to be sure to understand, all data are stored in the **leafletData** service according to the map Id ?

**Comment by nmccready** [comment]
Yes all data is in leafletData and fetched as a promise.

**Comment by claustres** [comment]
You will find an example to reproduce the issue attached to this post. I fetch two marker groups using $http and depending on the order you will see that only the first one is visible. Moreover if you switch to another example in the viewer and get back to this one you will see that sometimes no marker is visible at all.

Don't have time to debug yet but please let me know if I misunderstood something or if this is a known issue in case you have time to look at it. Thanks.

[clustering-group-issue.zip](https://github.com/angular-ui/ui-leaflet/files/71764/clustering-group-issue.zip)

**Comment by marquetd** [comment]
I confirm the problem. I have the same.

**Comment by wpanas** [comment]
I also noticed this problem. It occurs, when a new map is made with same groups' names. New markers are pushed to existing groups, but those groups are referencing to already destroyed DOM elements.

The dirty quick fix is to add `leafletMarkersHelper.resetMarkerGroups()` before pushing new markers to scope. 

If you give me a chance, I think that I could contribute and fix this issue.

**Comment by claustres** [comment]
Thanks for the tip anyway, tested and fixed my issue.

**Comment by nmccready** [comment]
@wpanas a PR is welcomed

**Comment by wpanas** [comment]
@nmccready I'm on it

**Comment by claustres** [comment]
Just to mention that it seems to remain another bug related to this. If I dynamically add/remove some markers from the marker list the clusters are not correctly updated. I need to force a digest cycle  in order to make sure that directive has cleared everything. Might be related to `_seeWhatWeAlreadyHave`...

**Comment by nmccready** [comment]
@wpanas #225
