### ISSUE TITLE
events not firing

### ISSUE THREAD

**Issue by lhammond** [angular-ui/ui-leaflet#216]
Hi, events are not firing for me.  Any tips on debugging this?  I tried configuring the nemLogging module to debug, but not seeing debugging, either.

I'm using ui-leaflet 1.0.0 2015-10-29

I've put a console.log on line 3364 and can see that the moveend event is getting detected.

here's what my code/markup looks like

 ```
angular.extend($scope, {
        center: {
            lat: 33.7677129,
            lng: -84.420604,
            zoom: 15
        },
        events: {
            map: {
                enable: ['layeradd','zoomstart','zoomend','drag', 'click', 'mousemove','moveend','mouseover'],
                logic: 'emit'
            }
        },
        layers: {
            baselayers: {
                osm: $scope.definedLayers.osm
            },
            overlays: {
                shapes: {
                    name: 'Shapes',
                    type: 'group',
                    visible: true
                }
            },
            paths:$scope.paths
        },
        defaults: {
            scrollWheelZoom: false
        }
    });

        var mapEvents = leafletMapEvents.getAvailableMapEvents();
        for (var k in mapEvents){
            var eventName = 'leafletDirectiveMap' + mapEvents[k];
            console.log("available event : " + eventName);
            $scope.$on(eventName, function(event){
                console.log("ok");
                $scope.eventDetected = event.name;
            });
        }
```

```
<leaflet
        id="map"
        defaults="defaults"
        class="lg_map"
        layers="layers"
        paths="paths"
        center="center"
        event-broadcast="events"
        events="events"
        height="445px" width="100%">
</leaflet>
```

**Comment by lhammond** [comment]
this was resolved by adding the id of the map to the event registration.

e.g. leafletDirectiveMap.lg_map.movend

also, per the logging, I found that I had to include leafletLogger in my controller and manually set the log level.

**Comment by davidrhoderick** [comment]
This doesn't work for me.  I copied the code exactly and it didn't work.  Is there a better explanation on how to do this?

**Comment by nmccready** [comment]
If your map does not have an id then you do not need it. Therefore no id would use `leafletDirectiveMap.movend`

**Comment by nmccready** [comment]
https://github.com/angular-ui/ui-leaflet/blob/master/examples/0501-markers-events-add-example.html#L24

https://github.com/angular-ui/ui-leaflet/blob/master/examples/0513-markers-events-example-with-id.html#L39-L44

**Comment by nighto** [comment]
I'm currently having the same problem. My JS code is like this:

    $scope.map = {
        events: {
            map: {
                enable: ['click'],
                logic: 'emit'
            }
        }
    };
    leafletLogger.currentLevel =  leafletLogger.LEVELS.debug;

    console.log('leafletMapEvents', leafletMapEvents, 'available map events', leafletMapEvents.getAvailableMapEvents());
    $scope.$on('leafletDirectiveMap.click', function(event, args){
        console.log(event, args);
    });

And HTML:

    <leaflet width="100%" height="280px" event-broadcast="map.events"></leaflet>

Checking console, I see the available map events, and when I click on the map I see leafletLogger debug log, but not the console.log of the event.

Any help is appreciated.
