### ISSUE TITLE
[$compile:ctreq] Controller 'leaflet', required by directive 'center', can't be found!

### ISSUE THREAD

**Issue by fxck** [angular-ui/ui-leaflet#217]
I'm getting this when trying to use leaflet inside an element directive(nothing special inside). Any ideas?

**Comment by fxck** [comment]
Nevermind, it was my fault all along.

**Comment by rajivhbk** [comment]
What was the issue? I'm facing same problem.

**Comment by fxck** [comment]
Can't remember. Sorry.
