### ISSUE TITLE
How to project pixel corrdinates in ui-leaflet

### ISSUE THREAD

**Issue by hkcity1111** [angular-ui/ui-leaflet#218]
Hi all,

Would anyone know how to do in ui-leaflet to project pixcel coordinate for image map such as in leaflet.js
Thanks for your advice.

    var northEast = map.unproject([674,0], map.getMaxZoom());
    var southWest = map.unproject([0, 250], map.getMaxZoom());
    map.setMaxBounds(new L.LatLngBounds(southWest, northEast));

BR
 Kenneth

**Comment by adgoncal** [comment]
```javaScript
leafletData.getMap('yourMapID')
  .then(function(map) {
    var northEast = map.unproject([674,0], map.getMaxZoom());
    var southWest = map.unproject([0, 250], map.getMaxZoom());
    map.setMaxBounds(new L.LatLngBounds(southWest, northEast))
  });
```

Don't forget to inject leafletData

**Comment by hkcity1111** [comment]
Hi adgoncal,

Thanks for you help

**Comment by elesdoar** [comment]
:+1: Thanks @adgoncal
