### ISSUE TITLE
Expose tileSize option

### ISSUE THREAD

**Issue by seadour** [angular-ui/ui-leaflet#219]
My tile server renders 512x512 px tiles, but the Leaflet default is 256x256.

In Leaflet, there is a `tileSize` option in `tileLayer` for adjusting this value, but I have been unable to access it through ui-leaflet. I tried setting it as part of `layerOptions` and `tileLayerOptions`.

Leaflet documentation on `tileSize`: http://leafletjs.com/reference.html#tilelayer-tilesize

**Comment by seadour** [comment]
I tried this in vanilla Leaflet -- no Angular -- and it's happening there too! Might be a Leaflet bug. I am closing this issue for now.

**Comment by nmccready** [comment]
Can you reference the issue in leaflet once one exists?

**Comment by seadour** [comment]
So, it's not a Leaflet bug. I reached out to Mapbox tech support since they are serving my tiles, and the issue was that I needed to also include `zoomOffsert: -1` in my `layerOptions`. I think this is probably true for any tile server, not just Mapbox.

**Comment by nmccready** [comment]
Cool thsnkd
