### ISSUE TITLE
Loading Google Tiles via HTTPS

### ISSUE THREAD

**Issue by that1guy** [angular-ui/ui-leaflet#220]
When I load google tiles (see below)

````
factory.map = {
    center: {
      lat: 'set by mainController.js',
      lng: 'set by mainController.js',
      zoom: 13
    },
    markers: {},
    layers: {
      baselayers: {
        google: {
          name: 'Satellite',
            layerType: 'HYBRID',
            type: 'google'
        }
      },
      overlays: {
        clusterLayer: definedOverlays.clusterLayer
      }
    }
  };
````

the dependencies are downloaded via http with is causing `mixed content` errors.  Is there a way I can require Leaflet to fetch these dependencies via https?

![https](https://cloud.githubusercontent.com/assets/1218940/12823943/97e2607c-cb23-11e5-84b8-2271d36077f0.png)

To be transparent this issue is also open in @tombatossals original   repository https://github.com/tombatossals/angular-leaflet-directive/issues/1059.  Thanks guys!

**Comment by nmccready** [comment]
Items:
- [google plugin is loaded](https://github.com/angular-ui/ui-leaflet/blob/1.X/src/services/leafletLayerHelpers.js#L179-L187) and [here](https://github.com/angular-ui/ui-leaflet/blob/1.X/src/services/leafletHelpers.js#L425-L435)

So there is nothing there specifying anything about transport. So my guess it is an issue with the plugin it's self. Also did you try loading the google sdk via https? Lastly can you make an example and is native leaflet with the google plugin working the same or differently?

**Comment by that1guy** [comment]
Thanks @nmccready, the solution to the issue was to add to my html:

`<script src="https://maps.google.com/maps/api/js?v=3"></script>`  and for what it's worth I tried this in the past, but instead I used removed the `http` and this did not work.. I had to include `https`

**Comment by nmccready** [comment]
Cool nice work
