### ISSUE TITLE
How to add to the mouseover and click events on markers

### ISSUE THREAD

**Issue by davidrhoderick** [angular-ui/ui-leaflet#227]
I am using a leaflet map to communicate with other elements on my page.  For example, when the user clicks on a marker, it should emit a custom event for me to update my other elements with information from that selected marker.

I don't need to know how to communicate between the map and other controllers, that is figured out.  My problem is, how do I listen to these map events?  I tried to follow another example in the issues and it didn't work.  What is the best way to listen to the map events regarding mousing over and clicking markers?

**Comment by claustres** [comment]
You can do something like this:
```
$scope.$on('leafletDirectiveMarker.map.mouseover', function(event, args){
      // Access underlying marker on leaflet object as args.leafletObject.options
});
```

Please have a look to http://angular-ui.github.io/ui-leaflet/examples/0000-viewer.html#/markers/events-add-example

**Comment by elesdoar** [comment]
Please check: 
http://angular-ui.github.io/ui-leaflet/examples/0000-viewer.html#/markers/events-example-with-id

This example shows how listen marker events.

**Comment by tharrington** [comment]
how do you get marker info for example the coords of the clicked marker?

**Comment by elesdoar** [comment]
Hi @tharrington 

Please check args param fields.
```js
$scope.$on('leafletDirectiveMarker.click', function(event, args){
  // Check args param has leafletEvent, this is leaflet click event that
  // contains latitude and logitude from click
  ...
});
```
