### ISSUE TITLE
Loading markers

### ISSUE THREAD

**Issue by vvavepacket** [angular-ui/ui-leaflet#230]
Lets say, we have 10000 markers spread all throughout the US. I want to load only the markers on the current map bounds/view instead of loading all 10000 at once. Is there any function already available for this one? If not, whats the best approach for this?

**Comment by nmccready** [comment]
Yeah you filter the markers before giving them to leaflet. Either by using a database like postgres or doing boundary checks via leaflet itself. I recommend using the database.

**Comment by vvavepacket** [comment]
So when we filter the markers, do you mean hosting those 10000 markers in a postgres database, then having a tile server that serves x/y/z.json?

**Comment by nmccready** [comment]
That depends on your use case. If you use markers or polygons as a tile server layer then you are limited in your interactions with that layer on the frontend. For example you will lose mouseover and click for specific markers/polygons. (think highlighting, getting details for a marker).

You do not need to serve up tiles just serve up geojson and box the markers your looking for by regions. I am not going to go into all the details here as this is everywhere on the internet by researching on google for postgres.

**Comment by nmccready** [comment]
http://gis.stackexchange.com/questions/83387/whats-the-fastest-way-to-do-a-bounding-box-query-in-postgis
