### ISSUE TITLE
How can I set the bounds of a map to fit all of the markers on a map?

### ISSUE THREAD

**Issue by chrismanderson** [angular-ui/ui-leaflet#234]
I feel like this should be simple, but I'm just missing something. Happy to add the solution to the examples page once I have it.

Thanks!

**Comment by adgoncal** [comment]
If you have all markers in a [featureGroup](http://leafletjs.com/reference.html#featuregroup), you can use `yourFeatureGroup.getBounds()`
If you need some padding, you can use the [pad()](http://leafletjs.com/reference.html#latlngbounds-pad) method on the returned bounds.

**Comment by chrismanderson** [comment]
Thanks for the response! So, I was following the examples on the [ui-leaflet](http://angular-ui.github.io/ui-leaflet/#!/examples/marker) page, and added my markers by following those examples, e.g:

    $scope.markers = [
      lat: 59.91,
      lng: 10.75,
      message: "I want to travel here!",
      focus: true,
      draggable: false
    ]

Not sure how to add them via a `featureGroup`; or, by adding the markers this way are they automatically added to a `featureGroup?` I see the link you pasted about featureGroups references the main leaflet documentation, but that seemed to be incorrect in context of this Angular project.

**Comment by adgoncal** [comment]
This was not tested, but may point you in the right direction:

```javaScript
$scope.markers = {
  marker1: {
    layer: 'markers', // This tells ui-leaflet to put this marker in the overlay with name 'markers'
    lat: 59.91,
    lng: 10.75,
    message: 'I want to travel here!',
    focus: true,
    draggable: false
  },
  marker2: {
    layer: 'markers', // This tells ui-leaflet to put this marker in the overlay with name 'markers'
    lat: 70,
    lng: 12,
    message: 'Another message',
    focus: true,
    draggable: false
  },
  // ...
};

$scope.overlays = {
  markers: {
    type: 'featureGroup',
    name: 'markers', // This is the name of the overlay
    visible: true
  }
};
```

**Comment by chrismanderson** [comment]
That sadly threw some error messages. I change my directive to 
`<leaflet markers="markers" layers="layers"></leaflet>`

and added the layer attribute to each marker, but I'm getting both a `Cannot read property 'baselayers' of undefined` and a ` A marker can only be added to a layer of type "group"` error.

**Comment by tharrington** [comment]
Did you figure this out?

**Comment by jackeo** [comment]
@chrismanderson You have found a solution to the error `Cannot read property 'baselayers' of undefined`? I too have the same problem ...

**Comment by elesdoar** [comment]
@jackeo, This error happen when layers attribute is not defined in the $scope.

Please assign a value to layers attribute as:

```js
$scope.layers = {
  baselayers: {},
  overlays: {}
}
```

**Comment by mehl321** [comment]
It may be a bit late but here is how I tackled this.

As per the documentation, inject `leafletData` into your controller.

Then you can do:
```JavaScript
leafletData.getMap().then((map) => {
    map.fitBounds(markersArray);
});
```

**Comment by cyrilchapon** [comment]
I might be stupid, but how to get raw leaflet `featureGroup` from angular scoped markers array / overlay option (/ geojson option in my case)
