### ISSUE TITLE
Using a computed map id causes some misnamed events

### ISSUE THREAD

**Issue by ezk84** [angular-ui/ui-leaflet#235]
This happens with a computed id, for example:

```html
    <leaflet id="{{:: mapId }}" center="center"></leaflet>
```

After this, map events will be named `leafletDirectiveMap.{{:: mapId }}.<event name>`. Note that marker events are not affected by this, they will be named correctly, e.g.: `leafletDirectiveMarker.the-map.popupopen`. 

Check [this plunkr](http://plnkr.co/edit/NBPc7dJOXR7ygNzavsqw?p=preview) for an MCVE.

I checked the code out and can trace this to one line in `src/services/events/leafletMapEvents.js`:

```javascript
    var _addEvents =  function(map, mapEvents, contextName, scope, logic){
        leafletIterators.each(mapEvents, function(eventName) {
            var context = {};
            context[contextName] = eventName;
            map.on(eventName, _genDispatchMapEvent(scope, eventName, logic, map._container.id || ''), context); // <<< right here!
        });
    };
```
At the stage that this function is being called (linking of the main leaflet directive) the `map._container.id` still hasn't been updated by angular, but luckily the mapId has already been saved for us in `scope.mapId` by the link function earlier.  So this should be a one line change (plus tests, of course).

**Comment by tzamagias** [comment]
Just thought I would add a comment here as I've been looking at doing the same thing.

My solution was to replace the above mentioned `map._container.id` with the existing `scope.mapId` that is set in the link function.
This fixed the events bug.
