### ISSUE TITLE
$destroy() not called at removing marker popup with directive (fixed, code inside)

### ISSUE THREAD

**Issue by vincent-ollivier-everysens** [angular-ui/ui-leaflet#240]
Hi there !

If you use an **angularjs directive** as a marker popup, when the marker is remove from path the `$destroy()` method is not call. It's a big problem when you deal with popups that  use two way binding or watchers, because they continue to live **after** the marker death ! This is a conceptual **bug**, who can potentially inflate memory and/or CPU.

I've done a jsfiddle with a corrected version of ui-leaflet.js who send a `$destroy() `on the `$scope` of popup directive. The directive finally receive the `$destroy event` and can do garbage stuff. 
Sorry if the fiddle is a little bit crowded, but I had to past all the ui-leaflet code in the javascript section. Just look at the very last lines, they describe a little angular `app`. 

**The way it works** => [jsFiddle](http://jsfiddle.net/icedfluid/u6ge21f2) :

1.  First ADD a marker with button. This will create marker with directive popup and a `$new() scope`.
2.  Then launch the popup by clicking on the marker. This will start a timer, have a look to the` console`.
3.  At least REMOVE the marker with button. This will remove it from path and trigger the` $destroy event` and let a chance to the directive to stop the timer and also, deeper inside Angular, kill the watchers for two way binding. 

## What I've done to correct it : 

At the end of  `_deleteMarker ` : ` markerData.getMessageScope().$destroy();`

![diff](https://cloud.githubusercontent.com/assets/17270874/13988489/7f51bc60-f10c-11e5-9d12-9b7012ddc6b8.png)

Can we rapidly mastering this evolution ? Pull request ?

Vincent

**Comment by ValentinH** [comment]
Hi Vincent,

I just found your issue while looking at random issues and I should have seen it sooner.

Indeed, I've submit a PR that fix a similar issue with DOM-markers: https://github.com/angular-ui/ui-leaflet/pull/273 which was merged. While I was fixing it, I was also thinking about popup with directives but since I don't use them, I didn't touch this part of the code...

**Comment by vincent-ollivier-everysens** [comment]
Nice Valentin !
It should fix this problem. I still use a custom fork of this project otherwise official version crash on my app.

**Comment by elesdoar** [comment]
Thanks for reporting.
