### ISSUE TITLE
Jumbled map tiles

### ISSUE THREAD

**Issue by MadEddieFFS** [angular-ui/ui-leaflet#246]
Has anyone seen something like this before?

![clipboard01](https://cloud.githubusercontent.com/assets/4107761/14611391/e2ab6e78-0589-11e6-91f8-9262f8febbcf.jpg)

I am using the total default....i.e. No Configuration
HTML:  `<leaflet width="100%" height="480px></leaflet>`

**Comment by seadour** [comment]
What URL are you using for your basemap?

Even though it's default configuration, can you post your `$scope.map` object for us just to be sure?

**Comment by MadEddieFFS** [comment]
There is no configuration in the controller....only the inclusion of 'nemLogging' and 'ui-leaflet'. Do I need a $scope.map = {} ?

**Comment by nmccready** [comment]
This is a normal symptom of div resizing. Is this happening? If so, you must tell leaflet to resize the map.

**Comment by seadour** [comment]
Oh, sorry, I wasn't aware we could use the directive without `$scope.map` explicitly defined.

**Comment by MadEddieFFS** [comment]
Thanks nmccready. Not too sure how I would do this but I do have the leaflet directive within a bootstrap row and col so I suppose having width set to 100% would indeed cause a resize. Any help would be appreciated

**Comment by nmccready** [comment]
- http://stackoverflow.com/questions/28868124/proper-implementation-of-invalidatesize-to-display-mapbox-leaflet-on-mobile-de
- http://stackoverflow.com/questions/16182032/how-can-you-make-a-leaflet-map-re-sizable

Figuring out how to do this via angular should be trivial. If not keep searching.
