### ISSUE TITLE
Adding PruneCluster to th layer control

### ISSUE THREAD

**Issue by zivlevy** [angular-ui/ui-leaflet#255]
Hi,

I am working on a project with more than 10K markers.
For performance I integrated PruneCluster which works excellent.

I am having trouble adding the PruneCluster layer to the layer control.
Can you advise how to do this ?

Ziv

**Comment by nmccready** [comment]
Yes this needs to be done. I believe there is an outstanding issue for this.
#54

Please feel free to spear head this.

**Comment by luntegg** [comment]
Still open? :(
