### ISSUE TITLE
[Question] Compatibility of ui-leaflet with leaflet.js 1.0.0-rc1

### ISSUE THREAD

**Issue by hkcity1111** [angular-ui/ui-leaflet#259]
Hi all,

Would anyone use with ui-leaflet with leaflet.js 1.0.0-rc1? 
I am using ui-leaflet with 0.77 version before and I find the z-index of map is changed so that I have to change my coding after trial run with leaflet.js 1.0.0-rc1. 
Is there any issue which I need to take care?
Thanks a lot!

Regards,
   Kenneth Lo

**Comment by nmccready** [comment]
1.0.0-X is being attempted in master which is targeting 2.X release. It has been pretty inactive as of late. 

Original plans were to continue using angular 1.X and modularize the library in general.

See #176

**Comment by hkcity1111** [comment]
Thanks @nmccready for your clarification

**Comment by elesdoar** [comment]
I will be working on this, soon. :construction_worker:
