### ISSUE TITLE
Service leafletDirectiveControlsHelpers is not passing the map ID to leafletData.getDirectiveControls()

### ISSUE THREAD

**Issue by tallented** [angular-ui/ui-leaflet#261]
In an application that has multiple maps on different pages, the directiveControls are being crossed and used for the incorrect map when re-displaying a map.  This appears to be happening because there is no map ID passed to a `leafletData.getDirectiveControls()` call in the file:

https://github.com/angular-ui/ui-leaflet/blob/master/src/services/leafletDirectiveControlsHelpers.js#L34

**Comment by nmccready** [comment]
confirmed will fix

**Comment by nmccready** [comment]
PR #262
