### ISSUE TITLE
How to enable search location/place feature?

### ISSUE THREAD

**Issue by saurabhnsonar** [angular-ui/ui-leaflet#270]
Hello,

How can I enable search control with the ui-leaflet? As I tried but didn't find it working anyway.

**Comment by Fidelsomething** [comment]
Hi, 
I stumbled upon the necessity to use some form of geocoding onto leaflet maps. Ended up extending the bounds with nominatim example to implement a rudimentar search box. As such, check it out and see if it helps you

**Comment by saurabhnsonar** [comment]
I upgraded the plugin code to support leaflet v1 and added http://esri.github.io/esri-leaflet/examples/geocoding-control.html it works perfectly, thanks for the advice!! :)

**Comment by elesdoar** [comment]
Seems that it's all done, thanks.
