### ISSUE TITLE
1.x branch, setting overlay visibility causes the opposite to happen

### ISSUE THREAD

**Issue by mtfurlan** [angular-ui/ui-leaflet#290]
So I'm using marker groups as overlay layers, as demonstrated in [example 0506](http://angular-ui.github.io/ui-leaflet/examples/0506-markers-groups-example.html). I was encountering an issue where digests were causing layer visibility to reset to the initial visibility set in the layer options.
When the watch defined on line [4205 of 1.X ui-leaflet.js](https://github.com/angular-ui/ui-leaflet/blob/1.X/dist/ui-leaflet.js#L4205) gets called, the layer visibility resets because changing layer visibility using the leaflet control doesn't change the actual visibility property as noted in [#28](https://github.com/angular-ui/ui-leaflet/issues/28). 

This issue wasn't reproducible in a smaller demo(which is kinda odd), so I decided to just set the visibility myself, as layers seemed to respect the visibility.

I took the marker group demo, and added event handlers for `overlayadd` and `overlayremove`, which set the visibility of the layer that changed. Also updated dependencies like leaflet to match my setup, but it happened in the versions initially in the demo as well.

            $scope.$on("leafletDirectiveMap.overlayadd", overlayAdd);
            $scope.$on("leafletDirectiveMap.overlayremove", overlayRemove);

            function overlayAdd(e,args){
                console.log("[MAP] Overlay add " + args.leafletEvent.name);
                $scope.layers.overlays[args.leafletEvent.name].visibility = true;
            }
            function overlayRemove(e,args){
                console.log("[MAP] Overlay remove " + args.leafletEvent.name);
                $scope.layers.overlays[args.leafletEvent.name].visibility = false;
            }

[Full source](http://sprunge.us/dViF).

What happens is that when you enable or disable a layer using the leaflet layer control, it calls the correct event, sets the visibility, which triggers angular-ui's watch on the overlays, but the `newOverlayLayers` somehow has the visibility wrong, causing the layer to be added/removed. It might be an angular issue? I don't know much about angular internals, and I'm not too keen to learn if I can avoid it right now.

Please note that the toggle buttons from the initial example still work, setting the visibility while not in the event handler still works.

Worst case, I can write my own custom control that only set the layer visibility, but this seems like the type of thing that's either trivial or incredibly hard to fix, so I'm just hoping it's the former.

Thank you.

**Comment by nmccready** [comment]
I will dig into this as I need to add some fixes to the 1.x branch for some null checks.

**Comment by nmccready** [comment]
@mtfurlan I am not sure if this is really a bug. To me it looks like the events you are tying into make sense and then your re-modify the property that triggered the watch to begin with. So you are causing s circular loop to undo what you started.

Removing the event handlers seems to have the desired behavior to me anyways.

http://jsbin.com/zifijej

**Comment by nmccready** [comment]
Ok, I modified the above jsbin a little more and I think I see your concern now. So basically `visible` is staying `false` regardless and not matching the layers actual state. Is this correct?

**Comment by nmccready** [comment]
So it appears that it was done internally one way in the layerControl probably on purpose. Anyways it needs some GTFO (get the *** out logic) to not circularly loop to make the layerControl reflect the correct state.

I am still trying to determine where this is.

**Comment by mtfurlan** [comment]
Yeah, `visible` not changing was the problem I was trying to work around. Issue #28 is that specific issue for visibility staying false. Fixing that would render this issue unnecessary, just odd behavior that isn't too important.
Thanks for looking into this so fast.

**Comment by nmccready** [comment]
Ok, disregard what I said earlier on the circular looping internally in ui-leaflet. The reason visible is staying false (one way changes) is because the default layer control is pure leaflet. It has no concept of updating our models. So you fiddling with visible after handling the leaflet event causing the circular loop makes sense.

If you need a layercontrol to actually turn things off and reflect state use. The layercontrol directive.

https://github.com/angular-ui/ui-leaflet/blob/1.X/examples/0400-controls-custom-layer-control-example.html

**Comment by mtfurlan** [comment]
Would you mind elaborating on why changing the visibility would start a circular loop?
The leaflet control shows the layer, and sends the event. I handle the event, and change the visibility in the ui-leaflet model. Shouldn't that just make ui-leaflet update leaflet and re-show the layer instead of disabling the layer?

I saw that control, but I prefer the way the native one looks. I can just go make a custom control at worst.

**Comment by mtfurlan** [comment]
Hahahahaha okay so I used `visibility` not `visible`.
My initial fix for the issue 28 works fine, I just need to set the right property.

The 'circular loop' as you put it was not a loop(which is why I was confused initially), but just applying the changed layer to the map, when none of the properties that were used changed, so nothing changed.
