### ISSUE TITLE
Compatibility with Leaflet.js 1.0.0?

### ISSUE THREAD

**Issue by htejwani** [angular-ui/ui-leaflet#298]
Is the ui-leaflet library compatible with Leaflet.js 1.0.0? The marker drag event is not working when upgraded to Leaflet.js 1.0.0.

**Comment by elesdoar** [comment]
We're working about it. Please check the branch [leaflet-1.X](https://github.com/angular-ui/ui-leaflet/tree/leaflet-1.X), project [Version 3.x](https://github.com/angular-ui/ui-leaflet/projects/1) and feel free for contribute on this.

Thanks for reporting. :smile:
