### ISSUE TITLE
When upgrading to ui-leaflet 2.0 I get errors on the layer types.

### ISSUE THREAD

**Issue by wesleyvandevoorde** [angular-ui/ui-leaflet#311]
After the upgrade everything keeps working except that I get errors in the console for all layers except the wmts layers. 

This is the error I get:[AngularJS - Leaflet] A layer must have a valid type: xyz,geoJSON,geoJSONShape,geoJSONAwesomeMarker,geoJSONVectorMarker,cartodbTiles,cartodbUTFGrid,cartodbInteractive,wms,wmts,group,featureGroup,markercluster,imageOverlay,iip,custom,cartodb

And here is an example of a layer I want to use: 
base: {
          name: 'Arcgis Topo',
            type: 'agsBase',
            layer: 'Topographic',
            visible: true,
            layerOptions: {
                reuseTiles: true,
                opacity: 1
            }
        }

So ui-leaflet seems to not recognise the agsBase type for a layer, same happens with agsDynamic layers. What am I doing wrong?

**Comment by nmccready** [comment]
Did you include https://github.com/elesdoar/ui-leaflet-layers ? ui-leaflet no longer provides everything under the sun. You must pull in other dependencies to complete what you had before.

**Comment by wesleyvandevoorde** [comment]
Including ui-leaflet-layers fixed it, wasn't very clear this had to be included to upgrade to the 2.0 version. Maybe this could be added to the changelog. Thanks for the 2.0 upgrade it works a lot faster/better!
