### ISSUE TITLE
Leaflet.label version 0.2.4 is not compatible with current directive version

### ISSUE THREAD

**Issue by sashberd** [angular-ui/ui-leaflet#318]
There is a new Leaflet.label 0.2.4 that not creates L.Label class extension, thus:

```
 LabelPlugin: {
      isLoaded: function() {
        return angular.isDefined(L.Label);
      },
```
will always return undefined and label will not build

**Comment by elesdoar** [comment]
Please try with Leaflet-1.X branch.

**Comment by sashberd** [comment]
Why I should use old version? Is there a problem to fix this in new version. I think problem is in if statement that I posted and Label object instance name.

**Comment by elesdoar** [comment]
This is not old version, this branch is for version 3.x, it integrates Leaflet 1.x.

**Comment by elesdoar** [comment]
Resolved in leaflet-1.X branch.
