### ISSUE TITLE
overlapping labels

### ISSUE THREAD

**Issue by vvavepacket** [angular-ui/ui-leaflet#325]
Is there any way to avoid overlapping labels? Like, we must tell the plugin to automatically find their optimum location so that they dont overlap each other. What approach is the best here? Thank you.

![image](https://snag.gy/7Q2KnA.jpg)

**Comment by elesdoar** [comment]
This is Leaflet issue, please report it on:

For Leaflet 0.7.x
https://github.com/Leaflet/Leaflet.label/issues

For Leaflet 1.x
https://github.com/Leaflet/Leaflet/issues
