### ISSUE TITLE
Issue to set id dynamically on the directive

### ISSUE THREAD

**Issue by marcelomiura** [angular-ui/ui-leaflet#336]
I have multiple maps on my view on custom directives, so I need to set the id to control them individually. I've tried to set the id dynamically with the timestamp, but when debugging the code, seems that it catches the id before angular replaces the databind:
`{{'mapid_' + ctrl.hash}}`
instead of:
`mapid_312343423`

I'm facing issues to detect events from each map. Any ideas?

**Comment by melgish** [comment]
Running into this same issue.  My (untested) thought was to create a directive that runs at a higher priority and sets the ID before leaflet can see it.

**Comment by elesdoar** [comment]
What ui-leaflet version was used?

**Comment by marcelomiura** [comment]
Version used is 1.0.3.
I've changed the code to get the map id from the mapId attribute on $scope instead of getting it from the map._container.id when adding the events and it seems to have fixed it so far:

`5315: map.on(eventName, _genDispatchMapEvent(scope, eventName, logic, map._container.id || ''), context);`

to

`5315: map.on(eventName, _genDispatchMapEvent(scope, eventName, logic, scope.mapId || ''), context);`

**Comment by elesdoar** [comment]
Please check #235, this issue was fixed, please use version 2.0.0.

Thanks.
