### ISSUE TITLE
Nor working in angular 1.6.4

### ISSUE THREAD

**Issue by janoskaz** [angular-ui/ui-leaflet#357]
The basic example does not work with angular 1.6.4. The tiles are out of order (see attachment).

The code is simple:

```
<div 
    id="ng-app" 
    ng-app="app" 
    ng-controller="appCtrl">
   <leaflet width="100%" height="480px"></leaflet>
</div>
```

![ui-leaflet](https://user-images.githubusercontent.com/5190988/42536435-988bc7c4-8481-11e8-853b-a10f957fe63e.png)

**Comment by elesdoar** [comment]
Please add the css file from leaflet in your html file.

```
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"  />
```

**Comment by janoskaz** [comment]
What a stupid mistake. Sorry for that.
