### ISSUE TITLE
Break of Fork to tombatossals/angular-leaflet-directive/

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#4]
Once website, examples, and docs are all fixed we can detach from the upstream fork.

**Comment by nmccready** [comment]
Request made, see bottom https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by nmccready** [comment]
If this cannot be done, I am not going to stress over it. It is mainly to avoid confusion.

**Comment by jessertaylor** [comment]
Looks like github accepted the request, closing.

**Comment by elesdoar** [comment]
Waooohh, great news... :+1:
