### ISSUE TITLE
Failed to load resource (file://...) for map tile on mobile device

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#40]
_From @mbmerrill on January 14, 2015 2:40_

I'm writing a mobile application using the Ionic framework and Leaflet.

If I use "base" Leaflet, I get my map on both the desktop browser (dev env) and on my mobile device when I deploy to it.

If I use this directive, I get my map on the desktop browser, but when I deploy to my mobile device I get (for example) "Failed to load resource file://a.tile.openstreetmap.org/1/0/0.png"

So it seems to me this indicates that somehow this directive is telling Leaflet to look for a local file instead of grabbing it from the openstreetmap site.

That's a useful feature (and one I will be using eventually), but I need to be able to fetch from the openstreetmap site too!  I tried setting the tiles.url in my angular.extend statement explicitly, which did not change the behavior.

What am I missing?

Thanks for your time.

_Copied from original issue: tombatossals/angular-leaflet-directive#602_

**Comment by nmccready** [comment]
_From @tombatossals on January 17, 2015 13:14_

Hi @mbmerrill , sorry I haven't used Ionic framework, but I can assure you this problem is not related with this directive, there's no configuration to look for local files.

Seems some problem with Ionic framework, if you post some example (jsfiddle) I can take a look at it.

**Comment by nmccready** [comment]
_From @pmusaraj on January 27, 2015 0:20_

I'm currently using this directive with Ionic, and I haven't run into this issue. The map loads the base layer from the web, same as on a browser, on the mobile device, not from a file:// call. You should try to find out why it's trying to load from a file...

**Comment by nmccready** [comment]
_From @bwasnie1 on January 29, 2015 15:3_

@mbmerrill It's because all urls in the directive are called like '//..' and not 'http://..'. I mentioned this aswell as I updated the directive to the latest version.

But I don't know yet, why ionic behaves like that.

**Comment by jlanio** [comment]
I have identical error using electron.
![as](https://cloud.githubusercontent.com/assets/10765588/25497707/16260ca8-2b4b-11e7-9532-e8ff2f368cb9.png)

**Comment by elesdoar** [comment]
Please check: http://angular-ui.github.io/ui-leaflet/examples/0000-viewer.html#/basic/custom-parameters-example

Assign a `tileLayer` param as:

```js
app.controller('BasicCustomParametersController', [ '$scope', function($scope) {
  angular.extend($scope, {
    london: {
      lat: 51.505,
      lng: -0.09,
      zoom: 8
    },
    defaults: {
      // check it
      tileLayer: "http://{s}.tile.openstreetmap.org/cycle/{z}/{x}/{y}.png",
      zoomControlPosition: 'topright',
      tileLayerOptions: {
        opacity: 0.9,
        detectRetina: true,
        reuseTiles: true,
      },
      scrollWheelZoom: false
    }
  });
}]);
```

**Comment by jlanio** [comment]
Unfortunately the error persists. @elesdoar

**Comment by elesdoar** [comment]
Are you using `defaults` attribute in the directive?

```html
<leaflet lf-center="london" defaults="defaults" width="100%" height="480px"></leaflet>
```

**Comment by jlanio** [comment]
@elesdoar 
> @jlanio, Are you using defaults attribute in the directive?

Exatly
