### ISSUE TITLE
Dynamic (ajax) message in pop-up

### ISSUE THREAD

**Issue by nmccready** [angular-ui/ui-leaflet#94]
_From @vksvicky on July 24, 2015 11:51_

Referring to ticket: https://github.com/tombatossals/angular-leaflet-directive/issues/600

I am having a problem with dynamic message, the problem being I am trying to invoke an AJAX call. So my code looks something like:

```
markers.push({
                                    id: 'abc_' + j,
                                    lat: abcLatLonOptions[j][0],
                                    lng: abcLatLonOptions[j][1],
                                    layer: 'abc',
                                    icon: {
                                        iconUrl: icons['abc'].icon,
                                        iconSize: [16, 16],
                                        popupAnchor: [0, 0],
                                    },
                                    message: complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed)
}
```
And 

```
 function  complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed) {
    var tide_level = 7.5;

    var tideWindowRequest = $.ajax({
                type: "GET",
                async: false,
                url: "https://api.sealevelresearch.com/1/predictions/tide-windows/liverpool-gladstone-dock/?start=" + startTime+ "Z&end=" + eta+ "Z&tide_level=" + tide_level,
                contentType: "application/json; charset=utf-8"
            });

return tideWindowRequest;
    }
```

I have tried to change  message to a function like

```
message: function(){
    complieAbcMessage(lat, lon, startTime, eta, calculatedEta, speed);
}
```

I get an error
```
TypeError: Argument 1 of Node.appendChild does not implement interface Node.
```

I have tried to play around without any success, any help would be appreciated. The reason I want it to be called inside a function is because the moment the marker is added to map, the complieAbcMessage function is called if I directly assign to message, which I don't want to do as I have over 1000 markers and that slow's the browser's response.

_Copied from original issue: tombatossals/angular-leaflet-directive#866_

**Comment by nmccready** [comment]
_From @MarkAPhillips on July 24, 2015 11:54_

Just a note - why are you using $.ajax - which is a jQuery wrapper- I suggest you use $resource or $http services to make the ajax request if you are build an angular app (which I assume you are if using this directive..)

**Comment by nmccready** [comment]
_From @vksvicky on July 24, 2015 12:9_

@MarkAPhillips, thanks for the note, I shall look up and make the necessary change, but don't think that will solve the problem, would it?

**Comment by nmccready** [comment]
_From @mikefedak on July 24, 2015 20:6_

So you are trying to get a tide table as a json? 

A leaflet popup requires that the content it displays is either html or string. If you do things the way you are, you are returning a promise and leaflet does not know how to deal with this. 

You should resolve you promise first and then populate your popup content. 

Just an idea- In the past when I had to populate async popup content I would write a directive and then pass the directive html element as the message. That way I could handle any logic/promises within the directive.

**Comment by nmccready** [comment]
_From @vksvicky on July 24, 2015 20:14_

Can you direct me to an example, its completely new to me. Also my return from the function call is like:
```
<b>Name:</b> ABC<br><b>Latitude: </b> xxx.xxx<br><b>Longitude: </b> xxx.xxx<br><b>Tide window: </b>: ... <br><b>Speed:</b> 22 kn
```

Where the tide window content is dependent on time I click the marker and I get a list of them and put them in a table format.

**Comment by nmccready** [comment]
_From @Wilzi on July 27, 2015 13:59_

Here is a working solution: http://jsfiddle.net/d2p19vn4/3/

**Comment by cscrum** [comment]
I looked at the fiddle on this and the examples, but I'm trying to pass a click event into the pop-up so that it can take me to another page. I'm not having much success. Can this be done? My markers are created dynamically from a customer database here is the function which creates the markers and what I've tried:

 for (c in $scope.cplans){

                var lt = $scope.cplans[c].lat;
                var ln = $scope.cplans[c].lon;

                var name = $scope.cplans[c].first + " " + $scope.cplans[c].last + " - " +$scope.cplans[c].cid;
                var addr =  $scope.cplans[c].Plan_Address + "<br>" + $scope.cplans[c].Plan_Address2 + $scope.cplans[c].Plan_City +", "+$scope.cplans[c].Plan_State+" "+$scope.cplans[c].Plan_Zip +"";
                var edlink = '<br><b><i><span ng-click="editCustomer(' + $scope.cplans[c].sid + ')">Edit</span></i></b>';
               
                var cmsg = "<h4>" + name + "</h4>" + addr + edlink;
                var sigcolor = "#FF0000";
                var ringcolor = "#FF0000";

                $scope.paths['cust_' + $scope.cplans[c].sid] = {};

                $scope.paths['cust_' + $scope.cplans[c].sid].color = ringcolor;
                $scope.paths['cust_' + $scope.cplans[c].sid].weight = 1;
                $scope.paths['cust_' + $scope.cplans[c].sid].type = 'circleMarker';
                $scope.paths['cust_' + $scope.cplans[c].sid].radius = 4;
                $scope.paths['cust_' + $scope.cplans[c].sid].clickable = true;
                $scope.paths['cust_' + $scope.cplans[c].sid].fillOpacity = 0.75;
                $scope.paths['cust_' + $scope.cplans[c].sid].fillColor = sigcol;
                $scope.paths['cust_' + $scope.cplans[c].sid].fill = true;
                $scope.paths['cust_' + $scope.cplans[c].sid].message = cmsg;
                $scope.paths['cust_' + $scope.cplans[c].sid].getMessageScope = function(){ 
                                                                                 var editCustomer = function(spid){
                                                                                    $state.go('app.customers.edit');
                                                                                 }
                                                                                 return editCustomer;
                                                                              } ;
                $scope.paths['cust_' + $scope.cplans[c].sid].compile = true;
                var cltln = {'lat': Number(lt), 'lng': Number(ln)};
                $scope.paths['cust_' + $scope.cplans[c].sid].latlngs = cltln;
                $scope.paths['cust_' + $scope.cplans[c].sid].layer = 'customers';

            }

**Comment by nmccready** [comment]
@cscrum we need a better example for your issue as a starting point

**Comment by nmccready** [comment]
@cscrum getMessageScope is only handled in markers it is not supported in paths yet. It looks like paths has no support for databinding via angular updates to the popup.

**Comment by nmccready** [comment]
Here here is the code here where the popup is bound. https://github.com/angular-ui/ui-leaflet/blob/master/src/directives/paths.js#L107-L109

So you need to compile the message and bind it to a custom controller before you pass it to angular-leaflet as a path.message.
